<a href="https://colab.research.google.com/github/Kartheek-777/TNS-Training/blob/main/Kaggle_Datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from google.colab import files

files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"kartheeklagisetti7","key":"232262fcf006d34eca9a6b69a1af248c"}'}

In [3]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.13/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.13/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.13/dist-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.13/dist-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kaggle) (26.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kaggle) (6.33.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.13/dist-packages (from kaggle) (9.1.2)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.13/dist-packages (from bleach->kaggle) (0.6.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (5.11.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.13/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (3.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (2026.7.22)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.12.2)

In [5]:
!kaggle datasets list

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                              title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating
---------------------------------------------------------------  --------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
dmitriigluzdov/casmi26-pubchem-popularity-prior                  CASMI26 PubChem Popularity Prior                    1286771429  2026-10-05 02:40:35.677000           6173         54                1
goodpjw2008/rsna-knee-2-5d-convnext-reader                       RSNA Knee 2.5D ConvNeXt reader                       353235670  2026-10-05 00:09:57.943000           5827         27           0.6875
srisyra02/zomato-market-analysis                                 Restaurant Market Analysis: Ratings, Prices             444049  2026-09-17 17:02:06.437000           5822        124                1
ahmedberatozer/casmi26-iceberg                                   casmi26-iceberg                                       64195893  2026-09-26 09:48:06.167000           7552         22            0.625
ahmedberatozer/casmi26-glacier                                   casmi26-glacier                                       56264835  2026-09-28 09:32:41.470000           7006         21            0.625
dreaddevelopment/raptor-knee-maxspan                             Knee MRI - Max-Span Dense Corpus                     271659195  2026-08-22 20:14:47.093000           1767         51           0.8125
dreaddevelopment/raptor-knee-native384dense                      Knee MRI - Native 384 Dense Corpus                   271657808  2026-08-23 13:17:23.333000            859         26           0.8125
ahmedberatozer/casmi26-fpnet-full1                               casmi26-fpnet-full1                                  184261486  2026-09-29 10:10:49.307000            829         11            0.625
dreaddevelopment/raptor-knee-native384                           Knee MRI - Native 384 Corpus                         271660739  2026-08-23 00:35:34.303000            787         25           0.8125
ahmedberatozer/casmi26-v3-models                                 casmi26-v3-models                                    374959744  2026-09-23 10:45:15.137000           3238          8            0.625
nartaa/rsna-knee-publication-swa-weights-20261007                RSNA Knee selected SWA weights 0949 and 0945         543312838  2026-10-07 19:26:38.967000           2634         17            0.625
anvithpothula/biohub-v1284-head-s075                             biohub v1284 head s075                                   30104  2026-09-20 14:13:26.057000           1041         35            0.875
prvsiyan/casmi26-fp-models-v2                                    CASMI26 fingerprint models (single + merged)         267281678  2026-09-16 22:50:48.873000           3311         10           0.6875
harishyadav0506/impact-of-social-media-on-life                   Impact of Social Media on Life                           78980  2026-09-09 18:10:54.497000           6392        106                1
dfranzen/pennyroyal-v253                                         pennyroyal-v253                                     6640272567  2026-09-29 14:28:58.637000          15471          2              0.5
samartalwar/sleep-debt-and-screen-time-late-night-phone-habits   Sleep Debt & Screen Time: Late Night Phone Habits       210821  2026-09-21 11:50:10.110000           3935         73                1
blixture/apple-stocks                                            Apple Inc. (AAPL) — SEC Financial Facts and Filing     1097035  2026-10-05 19:37:33.153000            807         30                1
datascikhan/e-commerce-sales-and-customer-analytics              E-Commerce Sales Analytics Dataset                    29815424  2026-08-25 08:00:46.013000          18329        358                1
dmitriigluzdov/casmi26-fold-safe-fpnet                           CASMI26 Fold-Safe FPNet: Training and Checkpoint     185992671  2026-09-30 16:14:23.977000           1334         13                1
eishatuzzuhra/ai-usage-and-impact-on-students-and-professionals  AI Usage and Impact on Students & Professionals          20123  2026-09-28 12:38:54.317000           1852         56                1

In [11]:
!kaggle datasets list -s E-Commerce Sales Analytics Dataset

usage: kaggle [-h] [-v] [-W]
              {competitions,c,datasets,d,kernels,k,models,m,files,f,benchmarks,b,config,auth} ...
kaggle: error: unrecognized arguments: Sales Analytics Dataset

In [12]:
!kaggle datasets download -d datascikhan/e-commerce-sales-and-customer-analytics

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/datascikhan/e-commerce-sales-and-customer-analytics
License(s): CC0-1.0
Downloading e-commerce-sales-and-customer-analytics.zip to /content
100% 28.4M/28.4M [00:02<00:00, 11.8MB/s]

In [14]:
!unzip -o e-commerce-sales-and-customer-analytics.zip

Archive:  e-commerce-sales-and-customer-analytics.zip
  inflating: customer_master.csv
  inflating: dataset_statistics.csv
  inflating: ecommerce_sales_customer_analytics_150k.csv
  inflating: order_items.csv
  inflating: product_catalog.csv

In [15]:
import pandas as pd

df = pd.read_csv('order_items.csv')
df.head()

,order_id,product_id,quantity,unit_price,discount_percentage,discount_amount,gross_sales,tax_amount,shipping_cost,net_sales,product_cost,profit
0,ORD-301242,PROD-000738,2,244.40,0.339607,166.00,488.80,22.60,6.48,351.88,173.28,172.12
1,ORD-301242,PROD-000181,3,287.13,0.362076,311.89,861.39,38.47,5.55,593.52,415.05,172.92
2,ORD-773460,PROD-000973,4,754.80,0.468300,1413.89,3019.20,305.01,9.00,1919.32,1976.16,-65.84
3,ORD-773460,PROD-000268,4,31.36,0.336182,42.17,125.44,15.82,0.00,99.09,55.72,43.37
4,ORD-449374,PROD-001040,3,6.31,0.089678,1.70,18.93,1.21,0.98,19.42,5.91,12.53

In [16]:
df.shape

(397569, 12)

In [17]:
df.size

4770828

In [18]:
df.dtypes

order_id                object
product_id              object
quantity                 int64
unit_price             float64
discount_percentage    float64
discount_amount        float64
gross_sales            float64
tax_amount             float64
shipping_cost          float64
net_sales              float64
product_cost           float64
profit                 float64
dtype: object

In [19]:
df.info

<bound method DataFrame.info of           order_id   product_id  quantity  unit_price  discount_percentage  \
0       ORD-301242  PROD-000738         2      244.40             0.339607
1       ORD-301242  PROD-000181         3      287.13             0.362076
2       ORD-773460  PROD-000973         4      754.80             0.468300
3       ORD-773460  PROD-000268         4       31.36             0.336182
4       ORD-449374  PROD-001040         3        6.31             0.089678
...            ...          ...       ...         ...                  ...
397564  ORD-252033  PROD-000792         2      137.53             0.156007
397565  ORD-252033  PROD-000804         5      118.96             0.097011
397566  ORD-252033  PROD-000527         3       52.50             0.141821
397567  ORD-528577  PROD-000004         1     1120.49             0.075121
397568  ORD-528577  PROD-000357         5      151.53             0.439653

        discount_amount  gross_sales  tax_amount  shipping_cost  net_sales  \
0                166.00       488.80       22.60           6.48     351.88
1                311.89       861.39       38.47           5.55     593.52
2               1413.89      3019.20      305.01           9.00    1919.32
3                 42.17       125.44       15.82           0.00      99.09
4                  1.70        18.93        1.21           0.98      19.42
...                 ...          ...         ...            ...        ...
397564            42.91       275.06       16.25           6.21     254.61
397565            57.70       594.80       37.60          14.89     589.59
397566            22.34       157.50        9.46          23.86     168.48
397567            84.17      1120.49       72.54           3.33    1112.19
397568           333.10       757.65       29.72           5.76     460.03

        product_cost  profit
0             173.28  172.12
1             415.05  172.92
2            1976.16  -65.84
3              55.72   43.37
4               5.91   12.53
...              ...     ...
397564        142.54  105.86
397565        280.80  293.90
397566         64.47   80.15
397567        564.86  544.00
397568        319.60  134.67

[397569 rows x 12 columns]>

In [20]:
df.describe

<bound method NDFrame.describe of           order_id   product_id  quantity  unit_price  discount_percentage  \
0       ORD-301242  PROD-000738         2      244.40             0.339607
1       ORD-301242  PROD-000181         3      287.13             0.362076
2       ORD-773460  PROD-000973         4      754.80             0.468300
3       ORD-773460  PROD-000268         4       31.36             0.336182
4       ORD-449374  PROD-001040         3        6.31             0.089678
...            ...          ...       ...         ...                  ...
397564  ORD-252033  PROD-000792         2      137.53             0.156007
397565  ORD-252033  PROD-000804         5      118.96             0.097011
397566  ORD-252033  PROD-000527         3       52.50             0.141821
397567  ORD-528577  PROD-000004         1     1120.49             0.075121
397568  ORD-528577  PROD-000357         5      151.53             0.439653

        discount_amount  gross_sales  tax_amount  shipping_cost  net_sales  \
0                166.00       488.80       22.60           6.48     351.88
1                311.89       861.39       38.47           5.55     593.52
2               1413.89      3019.20      305.01           9.00    1919.32
3                 42.17       125.44       15.82           0.00      99.09
4                  1.70        18.93        1.21           0.98      19.42
...                 ...          ...         ...            ...        ...
397564            42.91       275.06       16.25           6.21     254.61
397565            57.70       594.80       37.60          14.89     589.59
397566            22.34       157.50        9.46          23.86     168.48
397567            84.17      1120.49       72.54           3.33    1112.19
397568           333.10       757.65       29.72           5.76     460.03

        product_cost  profit
0             173.28  172.12
1             415.05  172.92
2            1976.16  -65.84
3              55.72   43.37
4               5.91   12.53
...              ...     ...
397564        142.54  105.86
397565        280.80  293.90
397566         64.47   80.15
397567        564.86  544.00
397568        319.60  134.67

[397569 rows x 12 columns]>